### Root endpoint
GET http://localhost:8888/health

### POST /signup
POST http://localhost:8888/signup
content-type: application/json

{
    "email": "mipruebahola.com",
    "name": "victor",
    "contact_person_email": "otrapruebas@hola.com",
    "contact_person_phone": "+16502530000",
    "diversity_type": "nada",
    "password": "pasdfasf"
}
