image: python:3.12-slim

stages:
  - test

pytest:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
  before_script:
    - python -V
    - pip install --upgrade pip
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  script:
    - pytest