"""
Live Session WebSocket Message Models

Defines the message protocol for real-time communication between
the mobile app and the backend during a live camera session.

Client → Server: frame (JPEG base64), audio_chunk (PCM base64)
Server → Client: alert, detection, status, error
"""

from enum import Enum
from typing import Literal, Optional
from pydantic import BaseModel, Field
from backend.ai.yolo.coco_taxonomy import COCOSupercategory
from backend.ai.yolo.domestic_risk import RiskLevel, RiskSource
from backend.ai.yolo.object_size import ObjectSizeCategory
from backend.ai.yolo.detection_zone import DetectionZone

# Client -> Server messages

class ClientMessageType(str,Enum):
    """
    Types of messages the client can send
    """
    FRAME = "frame"


class FrameTelemetry(BaseModel):
    """Client-side timing information associated with a captured frame."""

    frame_id: str = Field(..., description="Unique frame identifier generated by the client")
    capture_started_at: int = Field(..., description="Unix timestamp in ms when capture started")
    capture_finished_at: int = Field(..., description="Unix timestamp in ms when capture finished")
    encode_finished_at: int = Field(..., description="Unix timestamp in ms when base64 encoding finished")
    sent_at: int = Field(..., description="Unix timestamp in ms when the frame was sent to the backend")

class FrameMessage(BaseModel):
    """
    A single video frame captured by the device camera.
    Data is a JPEG imgage encoded as base64 string.
    Yolov26 expects JPEG/PNG input - base64 JPEG is the transport format.
    """
    type: Literal["frame"] ="frame"
    data: str = Field(..., description="Base64-encoded JPEG image")
    timestamp: float = Field(..., description="Unix timestamp (ms) when the frame was captured")
    telemetry: FrameTelemetry | None = Field(default=None, description="Optional client-side frame telemetry")


# Server -> Client messages

class ServerMessageTypes(str, Enum):
    """
    Types of messages the server can send
    """
    ALERT = "alert"
    DETECTION = "detection"
    STATUS = "status"
    ERROR = "error"

class AlertSeverity(str,Enum):
    """
    Severity levels for danger alerts
    """
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"

class DetectedObject(BaseModel):
    """
    A single object detected in the frame
    """
    class_name: str = Field(..., description= "COCO class name")
    confidence: float = Field(..., ge=0.0, le= 1.0, description="Detection confidence 0-1")
    bbox: list[float] = Field(..., min_length=4, max_length=4, description="Bounding box [x1, y1, x2, y2] normalized 0-1")
    track_id: int | None = Field(default=None, description="Stable tracker identifier across consecutive frames")
    zone: DetectionZone = Field(..., description="Vertical risk zone for detection")
    supercategory: COCOSupercategory = Field(..., description="Official COCO supercategory for the detected class")
    supercategory_risk_level: RiskLevel = Field(..., description="Domestic base risk level for the detected supercategory")
    supercategory_risk_weight: float = Field(..., ge=0.0, le=1.0, description="Domestic base risk weight for the detected supercategory")
    effective_risk_level: RiskLevel = Field(..., description="Effective domestic risk level after class override resolution")
    effective_risk_weight: float = Field(..., ge=0.0, le=1.0, description="Effective domestic risk weight after class override resolution")
    risk_source: RiskSource = Field(..., description="Source used to resolve the effective domestic risk")
    size_ratio: float = Field(..., ge=0.0,le=1.0,description="Bounding box area relative to image")
    size_category: ObjectSizeCategory = Field(..., description="Relative size category for the detected object")
    size_factor: float = Field(..., ge=0.0, le=1.0, description="Intermediate size prominence factor for the detected object")
    velocity_x_px_s: float | None = Field(default=None, description="Horizontal movement velocity in pixels per second")
    velocity_y_px_s: float | None = Field(default=None, description="Vertical movement velocity in pixels per second")
    speed_px_s: float | None = Field(default=None, ge=0.0, description="Movement speed magnitude in pixels per second")
    area_growth_ratio_2s: float | None = Field(default=None, ge=0.0, description="Bounding box area growth ratio compared with the same track 2 seconds earlier")
    is_approaching: bool = Field(..., description="Whether the tracked object has grown at least 20 percent over the last 2 seconds")
    track_age_ms: float = Field(..., ge=0.0, description="How long the current track has been alive in milliseconds")
    is_track_stable: bool = Field(..., description="Whether the track has remained alive long enough to be considered stable")
    object_risk: float | None = Field(default=None, ge=0.0, le=1.0, description="Final risk score for this object after combining semantic, proximity and motion factors")

class AlertMessage(BaseModel):
    """
    Danger alert sent to the client when a hazardous object is detected.
    The client should notify the user.
    """
    type: Literal["alert"] = "alert"
    message: str = Field(..., description="Human-readable alert message")
    severity: AlertSeverity = Field(..., description="Alert severity level")
    objects: list[DetectedObject] = Field(default_factory=list, description="Objects that triggered the alert")
    timestamp: float = Field(..., description="Server unix timestamp (ms)")


class DetectionTelemetry(BaseModel):
    """End-to-end timing information returned to the client for a processed frame."""

    frame_id: str | None = Field(default=None, description="Client-generated frame identifier")
    capture_started_at: int | None = Field(default=None, description="Client timestamp in ms when capture started")
    capture_finished_at: int | None = Field(default=None, description="Client timestamp in ms when capture finished")
    encode_finished_at: int | None = Field(default=None, description="Client timestamp in ms when encoding finished")
    sent_at: int | None = Field(default=None, description="Client timestamp in ms when the frame was sent")
    server_received_at: int = Field(..., description="Server timestamp in ms when the frame was received")
    server_responded_at: int = Field(..., description="Server timestamp in ms when the response was emitted")
    processing_ms: float = Field(..., description="Backend processing time in ms")

class SceneRiskAssessment(BaseModel):
    """
    Aggregated risk information for the current frame or scene
    """
    instant : float = Field(..., ge=0.0, le=1.0, description="Aggregated scene risk computed from the current frame only")
    smoothed: float = Field(..., ge=0.0, le=1.0, description="Temporally smoothed scene risk used for more stable decisions")
    severity: AlertSeverity = Field(..., description="Severity derived from the smoothed scene risk")
    dominant_object_index: int | None = Field(default=None, ge=0, description="Index of the object with the highest object_risk in the objects array")
    dominant_track_id: int | None = Field(default=None, description="Track identifier of the highest risk object when available")
    dominant_class_name: str | None = Field(default=None, description="Class name of the highest risk object when available")


class DetectionMessage(BaseModel):
    """
    Raw detection results for a processed frame.
    Useful for debugging / visualization on the client
    """
    type: Literal["detection"] = "detection"
    objects: list[DetectedObject] = Field(default_factory=list, description="Objects detected in the frame")
    frame_timestamp: float = Field(..., description="Original frame timestamp")
    procesing_ms: float = Field(..., description="Time taken to process the frame in ms")
    telemetry: DetectionTelemetry | None = Field(default=None, description="Optional end-to-end telemetry for the processed frame")
    scene_risk: SceneRiskAssessment | None = Field(default=None, description="Aggregated risk assessment for the current frame")
    
class StatusMessage(BaseModel):
    """
    Connection or processing status update
    """
    type: Literal["status"] = "status"
    status: str = Field(..., description="Status indentifier (connected, processing, ready)")
    message: Optional[str] = Field(default=None, description="Optional human-readable detail")

class ErrorMessage(BaseModel):
    """
    Error message sent to the client
    """
    type: Literal["error"] = "error"
    message: str = Field(..., description="Error description")
    code: Optional[str] = Field(default=None, description="Error code for programmatic handling")

    